# -- Web site root --
# The web container uses /var/www/html as site root. Make sure the html  dir is
# available or has is symlinked correctly.
#
# 'password' => getenv('MYSQL_ENV_MYSQL_ROOT_PASSWORD'),
# 'host'     => getenv('MYSQL_PORT_3306_TCP_ADDR'),

drupal-kraftwagen-build:
  build: ./drupal-kraftwagen
  volumes:
    - ./drupal-kraftwagen/src:/home/drupal/src
    - ./drupal-kraftwagen/cnf/settings.local.php:/home/drupal/cnf/settings.local.php
    - ./drupal-kraftwagen/cnf/enviroment:/home/drupal/cnf/enviroment
    - ./drupal-kraftwagen/cnf/files:/home/drupal/cnf/files
    - /var/www/html
data:
  image: ubuntu:14.04
  volumes:
    - /var/logs
db:
  image: mysql:5.7.8
  environment:
    - MYSQL_ROOT_PASSWORD=root
  volumes_from:
    - data
web:
  build: ./php
  expose:
    - 80
  ports:
    - 80:80
  links:
    - db:mysql
  volumes_from:
    - drupal-kraftwagen-build
    - data
